### PR TITLE
Use load-jsonic-sync to load json with comments and report position and filename in error messages

### PR DESCRIPTION
**Pull request by aredridel**
Gives errors like 

```
VError: loading jsonic file 'test/fixtures/malformed/config.json': pair rule failed at: 1:3


{
  ^
    at loadJsonicSync (node_modules/load-jsonic-sync/index.js:10:15)
```

instead of

```
SyntaxError: Unexpected token }
    at Object.parse (native)
```

### CODE REVIEW

**Comment by jasisk** [comment]
Can we get an sample error message (demonstrate the value)?

**Comment by aredridel** [comment]
Edited!

**Comment by jasisk** [comment]
Worth pointing out that, though this is replacing the natively provided json parsing implementation, Aria's JSON parser is [testing against a suite](https://github.com/aredridel/json-ometajs/tree/master/test/cases) as defined in [JSON for Modern C++](https://github.com/nlohmann/json).

**Review by grawk — APPROVED** [review]
Looks good to me!

**Pull request merged**
