### PR TITLE
Minor es6 cleanup - switch to Object.assign

### PR DESCRIPTION
**Pull request by jasisk**
Just a small cleanup leveraging `Object.assign`.

### CODE REVIEW

**Comment by aredridel** [comment]
o.O

Kinda torn whether that makes things more readable.

**Comment by jasisk** [comment]
I like the object literal shorthand of it all but I could certainly go either way.

**Comment by totherik** [comment]
Yeah, especially in the context of line 33 which sets `this.promise`. Also, it adds unnecessary overhead.

**Comment by jasisk** [comment]
Whelp. Alrighty then.

**Pull request closed without merging**
